f = open('sample.txt', 'r')
print(f.read())
f.seek(0)
print(f.read(3))
f.seek(0)
print(f.readline())
f.seek(0)
print(f.readline(3))
f.seek(0)
print(f.readlines())
f.seek(0)
print(f.readlines()[1])
f.close()